import type { Metadata } from 'next';

import { Container } from '@repo/ui/src/components/molecules/container';
import { SessionProvider } from '@repo/ui/src/components/molecules/sessionProvider';
import '@repo/ui/src/index.css';
import { Navbar } from '@repo/ui/src/components/organisms/navbar';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'turborepo template | zackinfosbd@gmail.com',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <Navbar />

          <Container>{children}</Container>
        </SessionProvider>
      </body>
    </html>
  );
}
