name: CI

on:
  push:
    branches: ['main', 'staging']

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node.js environement
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pmpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
